package:
  version: "{{ PROJECT_VERSION }}"
  name: 'nclsx'

source:
  path: ../../

build:
  script_env:
   - PROJECT_VERSION
  number: 0
  script: python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython >=0.24.1
    - setuptools
    - nose
  run:
    - numpy
test:
  requires:
    - python
    - numpy
    - cython
  imports:
    - nclsx
#  commands:
#    - conda inspect linkages nclsx
#    - nosetests -v --detailed-errors nclsx

about:
  description: Demo python+cython project
  home: https://github.com/jianlins/pnclsx
  license: New BSD License

extra:
  recipe-maintainers: Jianlin Shi <jianlinshi.cn@gmail.com>
